[project]
name = "hexlet-code"
version = "1.0.0"
description = "Page Analyzer"
dependencies = [
    "flask",
    "python-dotenv",
    "gunicorn",
    "flake8",
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"